### ISSUE TITLE
[Deployment] - Update GitHub action to block fail deployment to Staging if possible

### ISSUE THREAD

**Issue by rcs-tringuyen** [associatedG/pmso-service#23]
As per title

**Comment by LongNgg** [comment]
Case của t là do generator t k chỉnh đúng, có lúc nó generate ra valid VN phone number lúc không, lúc PR thì nó pass còn lúc vô staging thì k được. T coi lại xong mới fix rồi chứ bth là không được.

**Comment by rcs-tringuyen** [comment]
Cannot use GitHub check in branch setting because it will block user from merging

**Comment by rcs-tringuyen** [comment]
Not feasible as of now. Consider changing the branch name to test and maybe the app service name too.
